### ISSUE TITLE
Issues reproducing paper results (hypernerf-vrig)

### ISSUE THREAD

**Issue by gmkwon-prev** [raven38/EfficientDynamic3DGaussian#10]
Thanks for releasing the code.

I need help reproducing the paper's results with the current codebase.

I ran on the Hypernerf vrig dataset, chicken and broom with L=5.
I expected the results in the paper in Table 3.
I ran with no flow loss and no lasso loss like your setting "process_hypernerf.sh"

I think something was missed during my experiment.
I just downloaded the code and dataset.
Then ran train.py, render.py, and metrics.py.

I've included some screenshots of the PSNR and results. 
vrig-chicken (24.47 / 28.3 on Table 3)
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/aa04c30c-8d34-4925-912e-ddecb740ac49">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/8fd3e274-eece-4866-a5de-3b9fa0f446d5">

vrig-broom2 (20.00 / 22.1 on Table 3)
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/f5a97ad8-0983-4753-9609-4d2fc1b73d0e">
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/174c7b5b-a583-4c9f-8def-6453aaa4c887">

**Comment by raven38** [comment]
Sorry for your inconvenience. As mentioned in our paper, we use COLMAP sparse points for initial 3D Gaussians. You can use the dataset to train the hypernerf scenes.  
https://drive.google.com/drive/folders/11o1A7K0EUKqpeHISZVnqRxLZVSK3wU6_?usp=drive_link
We also updated the codebase for the hypernerf scenes (disable white background).

Thank you for your reports.

**Comment by gmkwon-prev** [comment]
I'm really happy to your kind answer!

Unfortunately, I cannot access to your Link of google drive.
I send you a access request.
Could you approve me to access your link, or turn your link open?

Thank you again for your open code, and kind answer.

**Comment by raven38** [comment]
@gmkwon-prev I think you can access to the link now.
