### ISSUE TITLE
Issues reproducing paper results

### ISSUE THREAD

**Issue by dlazares** [raven38/EfficientDynamic3DGaussian#2]
Hi thanks for writing the paper and releasing the code!

I'm having trouble reproducing the results of the paper with the current codebase. 

I ran on the DyNerf sear steak dataset with L=5 and no flow loss and I'm not getting close to the results y'all are getting. I expected it to look like the ablation on the left in Figure 5.

Maybe a bug or something is missing in the released code?

I've included some screenshots of the PSNR and results. The train PSNR is close to the paper results but visually the results don't look the same and the eval PSNR is far from the paper reported number.

<img width="1907" alt="efficient_flame_steak_30k_repro_fail" src="https://github.com/raven38/EfficientDynamic3DGaussian/assets/10122282/9ec36f0c-003c-40c9-a246-111ef79b4d89">

<img width="1898" alt="eff_flame_steak_30k_test_repro_fail" src="https://github.com/raven38/EfficientDynamic3DGaussian/assets/10122282/84397dd0-a0d1-4b03-ad15-f58e99a79e1c">

**Comment by raven38** [comment]
Thank you for reporting issues. I also reproduced worse results like yours. 
The wrong input resolution causes the behavior. 
The codebase assumes the DyNeRF dataset with 1352 × 1014. 
https://github.com/raven38/EfficientDynamic3DGaussian/blob/fffde7c4da2c3ea50f977d4ac514a4cf5182938d/scene/dataset_readers.py#L500-L503
When the input images are 2704x2028, I can reproduce the worse results.

Would you check the input resolution and downsample the images or set 1 to `downsample`?
