### ISSUE TITLE
Question for _fwd.npz and _bwd.npz

### ISSUE THREAD

**Issue by robot0321** [raven38/EfficientDynamic3DGaussian#3]
Hi, thanks for the interesting work!

When I ran your code, it outputs a degraded image.
So I check your code, and it seems there is no flow data from RAFT (_fwd.npz and _bwd.npz, L47-48 in camera_utils.py)
Could you provide the files or could you explain how to make the .npz files from RAFT?
Thank you for your time!

**Comment by raven38** [comment]
We use the code based on https://github.com/princeton-vl/RAFT and raft-sintel.pth the original authors provided. 
We updated the repository. Please check the `script/flow_dynerf_all.sh`.
For the issue of degraded images, another issue may help you https://github.com/raven38/EfficientDynamic3DGaussian/issues/2

Thank you for your interest in our work.
