### ISSUE TITLE
Cant get train.py working

### ISSUE THREAD

**Issue by josephldobson** [raven38/EfficientDynamic3DGaussian#4]
Optimizing 
Output folder: ./output/5d886479-c [19/03 14:22:16]
Tensorboard not available: not logging progress [19/03 14:22:16]
Reading camera 268/268 [19/03 14:22:17]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [19/03 14:22:17]
Traceback (most recent call last):
  File "train.py", line 274, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 40, in training
    scene = Scene(dataset, gaussians)
  File "/home/joe/Documents/3DGS/EfficientDynamic3DGaussian/scene/__init__.py", line 129, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/home/joe/Documents/3DGS/EfficientDynamic3DGaussian/scene/dataset_readers.py", line 278, in readColmapSceneInfo
    ply_path=ply_path)
TypeError: __new__() missing 2 required positional arguments: 'vis_cameras' and 'time_delta'

I ran your convert.py file to process a set of images, i'm unable to get this working, can you help?

**Comment by raven38** [comment]
Thank you for sharing your inconvenience.
I updated the code. Please pull up-to-date repository.
