### ISSUE TITLE
Question about your flow  rendering

### ISSUE THREAD

**Issue by Mobiuslqm** [raven38/EfficientDynamic3DGaussian#6]
Hi, Kai , Thank your for openning source your codes.

is this line of code transform xyz in world space to cam space? 
[https://github.com/raven38/EfficientDynamic3DGaussian/blob/3d3383c93c38a276fe5310686e007c7fdc059128/gaussian_renderer/__init__.py#L231](url)
if it is , i think it may be wrong? 
Shouldn't it be  `t = torch.matmul(means3D,viewmatrix[:3,:3])+ viewmatrix[3, :3] `?
best regards.

**Comment by raven38** [comment]
Thank you for pointing out.

I confirmed that the transformation causes minor effects.
