### ISSUE TITLE
目前4D高斯发展情况？

### ISSUE THREAD

**Issue by chenqi13814529300** [raven38/EfficientDynamic3DGaussian#7]
我不是很了解4D高斯，现在的训练只支持特别小的数据吗，我看每次发的demo都是很小的数据集，相比于3D高斯，相同场景下相比，训练慢多少？

**Comment by raven38** [comment]
You can see the results for large scenes and the training time in the figures and tables in our paper. 
https://arxiv.org/abs/2311.12897
