### ISSUE TITLE
Loss is NAN and Tenosr Size Error for my own colmap datasets

### ISSUE THREAD

**Issue by JaNg2333** [raven38/EfficientDynamic3DGaussian#9]
Hi, when I use my own scene data obtained by the convert.py to train your project, the loss is nan and occur the tensor size error. Can you help me solve this problem?
```
Training progress:  10%|█████▏     | 3000/30000 [01:30<13:46, 32.67it/s, Loss=nan, Flow loss=0.0000000]
Traceback (most recent call last):
  File "train.py", line 274, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 108, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background, itr=iteration)
  File "/data/EfficientDynamic3DGaussian/gaussian_renderer/__init__.py", line 69, in render
    means3D = pc.get_xyz[:, 0, :] + (pc.get_xyz[:, 1:2*L+1, :]*basis.unsqueeze(-1)).sum(1)
RuntimeError: The size of tensor a (0) must match the size of tensor b (4) at non-singleton dimension 1
```

**Comment by Larissa0829** [comment]
Hello! I'm having the same issue, have you solved it?

**Comment by raven38** [comment]
Sorry for your inconvenience. I added these lines to avoid the error. 
If you have any questions, please feel free to ask.

https://github.com/raven38/EfficientDynamic3DGaussian/blob/3759aca592bc20ba5e43d84611d84d0d11163583/scene/dataset_readers.py#L407-L409

**Comment by raven38** [comment]
Sorry for your inconvenience. I added these lines to avoid the error. 
If you have any questions, please feel free to ask.

https://github.com/raven38/EfficientDynamic3DGaussian/blob/3759aca592bc20ba5e43d84611d84d0d11163583/scene/dataset_readers.py#L407-L409

**Comment by JaNg2333** [comment]
> Hello! I'm having the same issue, have you solved it?

I abandon
